version: '3'
services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: faroese-radio
    networks:
      - webnet
  web:
    image: faroese-radio
    ports:
      - '8081:8081'
    networks:
      - webnet
    environment:
      DB_HOST: db
    command: ['./wait-for-it.sh', 'db:5432', '--', 'npm', 'start']
networks:
  webnet: