version: '3'
services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: faroese-radio
    ports:
      - 5433:5432
    volumes:
      - ./10-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/var/lib/postgresql/data
    networks:
      - webnet
  web:
    volumes:
      - ./app:/app
    build: .
    ports:
      - 8081:8081
    networks:
      - webnet
    environment:
      DB_HOST: db
    command: ['/wait-for-it.sh', 'db:5432', '--', 'npm', 'run', 'init-start']
networks:
  webnet: